### PR TITLE
OIDC plugin

### PR DESCRIPTION
**Pull request by stefanvanherwijnen**
I moved the swagger views directory to the `src` folder because otherwise there would be two root dirs in the views Configuration.
I tested initializing a project with either swagger or oidc, and both and everything seems to work.

The src folder which is copied in the cli-plugin-oidc-provider is basically a copy of the test/app folder in the oidc plugin and thus matches the documentation 1:1.

"OpenID Connect provider" can be selected as a feature and everything should work out of the box (apart from the correct OIDC configuration). Generating OIDC configurations with the CLI could possibly be a feature in the future by rendering it into oidcConfig.hbs (e.g. defining clients on initialization).

### CODE REVIEW

**Comment by Romakita** [comment]
Awesome :D

**Comment by Romakita** [comment]
arf... but views directory must be outside /src to preserve path when you build application

**Comment by Romakita** [comment]
Exactly the views isn't copied by the yarn buid / tsc. It's normal, this is why I prefer to set the views outside src to preserve the relative paths between `src` and `build` directories. I'll push a commit to fix that :)

**Comment by stefanvanherwijnen** [comment]
It looks like NestJS also has `views` outside the `src` folder (https://docs.nestjs.com/techniques/mvc#model-view-controller). It's up to you, but to me it makes more sense that `src` compiles to `dist` and everything necessary is included. Otherwise you might end up hosting the `dist` folder and it won't work because you forgot to copy the `views` folder manually (or are required to keep the entire git repo checked out on your hosting server).

**Comment by Romakita** [comment]
Yes sure but the build is performed by `tsc` and tsc doesn't make a copy of the views directory or other directories that haven't ts files. Basically, the project works without extra command if the views directory is outside the `src` ^^. After, if the developer want to add extra command to copy the views, it can :)

**Comment by Romakita** [comment]
@stefanvanherwijnen I released a new version with two fix:
- one about the npm published package (missing files in archive)
- one about the oidcbasePath ^^

the release is on going. You will be able to test your works with the v3.10.2

**Comment by stefanvanherwijnen** [comment]
https://github.com/tsedio/tsed-cli/blob/67a0a6944c4c811edcea0d5bd860a08daa8902e7/packages/cli-plugin-oidc-provider/templates/init/src/controllers/oidc/InteractionsCtrl.ts.hbs#L10
InteractionCtrl is not and should not be mounted at the oidc basePath 😉. Interactions are completely separate from oidc-provider.

**Comment by stefanvanherwijnen** [comment]
Actually, it seems to work fine. I expected oidc-provider to return a 404.
One issue, the renderAll function contains a few errors.
Should be:
```js
          this.rootRenderer.renderAll(
            [
              "/src/config/oidc/index.ts.hbs",
              "/src/controllers/oidc/InteractionsCtrl.ts.hbs",
              "/src/interactions/ConsentInteraction.ts",
              "/src/interactions/CustomInteraction.ts",
              "/src/interactions/LoginInteraction.ts",
              "/src/models/Account.ts",
              "/src/services/Accounts.ts",
              "/views/forms/interaction-form.ejs.hbs",
              "/views/forms/login-form.ejs.hbs",
              "/views/forms/select-account-form.ejs.hbs",
              "/views/partials/footer.ejs",
              "/views/partials/header.ejs",
              "/views/partials/login-help.ejs.hbs",
              "/views/interaction.ejs",
              "/views/login.ejs",
              "/views/repost.ejs.hbs"
            ].filter(Boolean),
            ctx,
            {
              templateDir: `${TEMPLATE_DIR}/init`
            }
          )
```

**Comment by Romakita** [comment]
> https://github.com/tsedio/tsed-cli/blob/67a0a6944c4c811edcea0d5bd860a08daa8902e7/packages/cli-plugin-oidc-provider/templates/init/src/controllers/oidc/InteractionsCtrl.ts.hbs#L10
> 
> InteractionCtrl is not and should not be mounted at the oidc basePath 😉. Interactions are completely separate from oidc-provider.
> 
> https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#user-flows

Ok. I didn't know that but it doesn't make a lot of sense to me. There is no security reason behind that that would impose this kind of rule. ^^

I correct the cli suddenly.

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed-cli/pull/159

**Comment by stefanvanherwijnen** [comment]
My guess was that because oidc-provider is its own koa instance, mounting `/interactions` under the oidc basePath would result in a 404 because the routes would not be registered in the koa instance. But I was wrong and it did seem to work (probably because of `interactionsUrl`).
I do think it is better to keep `/oidc` limited to just oidc-provider, and mount any user implementations (interactions) somewhere else (to make it more clear that they are not part of oidc-provider and to prevent any errors which might occur when mounting them under the basePath of the oidc-provider koa instance).
I'll give the recent changes a test, thanks :+1: .

**Comment by stefanvanherwijnen** [comment]
https://github.com/tsedio/tsed-cli/blob/ac500c2c1947934696bf9a74c8dc6f67304e8896/packages/cli-plugin-oidc-provider/templates/init/src/controllers/oidc/InteractionsCtrl.ts.hbs#L10
Should be just "/interaction/:uid" now. With that change it all seems to work.

**Comment by Romakita** [comment]
Fix is on going.

**Pull request merged**
